import { ClipboardCheck, Map } from "lucide-react";
import Link from "next/link";
import { SectionLabel } from "@/components/section-label";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getLatestCompletedAssessment } from "@/lib/data-access/assessments";
import { getCompany } from "@/lib/data-access/companies";
import { orNotFound, requireOrgPageContext } from "@/lib/data-access/page-context";
import { listRoadmapItemsFor } from "@/lib/data-access/roadmap";
import { GenerateRoadmapButton, RoadmapItemCard } from "./roadmap-view";

export const metadata = { title: "Roadmap" };

export default async function RoadmapPage({
  params,
}: {
  params: Promise<{ companyId: string }>;
}) {
  const { companyId } = await params;
  const ctx = await requireOrgPageContext();

  const [company, assessment] = await orNotFound(() =>
    Promise.all([
      getCompany(ctx, companyId),
      getLatestCompletedAssessment(ctx, companyId),
    ]),
  );
  const items = assessment ? await listRoadmapItemsFor(ctx, assessment) : [];
  const doneCount = items.filter((i) => i.status === "done").length;

  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div className="space-y-1">
          <SectionLabel>Roadmap</SectionLabel>
          <h1 className="text-3xl font-bold text-primary">{company.name}</h1>
          <p className="text-muted-foreground">
            {items.length > 0
              ? `${doneCount} of ${items.length} steps done — generated by rules from your readiness assessment.`
              : "A prioritised action plan generated from your readiness assessment."}
          </p>
        </div>
        {assessment && (
          <GenerateRoadmapButton
            assessmentId={assessment.id}
            companyId={company.id}
            hasItems={items.length > 0}
          />
        )}
      </div>

      {!assessment ? (
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center gap-4 py-16 text-center">
            <div className="flex size-14 items-center justify-center rounded-full bg-muted">
              <ClipboardCheck className="size-6 text-primary" />
            </div>
            <div className="space-y-1">
              <p className="font-semibold text-primary">No completed assessment yet</p>
              <p className="max-w-sm text-sm text-muted-foreground">
                The roadmap is derived from your readiness answers — complete the
                assessment first.
              </p>
            </div>
            <Button asChild>
              <Link href={`/companies/${company.id}/assessment`}>
                Start the assessment
              </Link>
            </Button>
          </CardContent>
        </Card>
      ) : items.length === 0 ? (
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center gap-4 py-16 text-center">
            <div className="flex size-14 items-center justify-center rounded-full bg-muted">
              <Map className="size-6 text-primary" />
            </div>
            <p className="max-w-sm text-sm text-muted-foreground">
              Generate the roadmap to turn the weaknesses detected in the assessment
              into an ordered action plan.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {items.map((item, index) => (
            <RoadmapItemCard
              key={item.id}
              item={item}
              index={index}
              companyId={company.id}
            />
          ))}
          <p className="pt-2 text-xs text-muted-foreground">
            Rules {items[0].rulesVersion} · assessment of{" "}
            {assessment.completedAt!.toLocaleDateString("en-GB", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
            . Durations are indicative planning estimates.
          </p>
        </div>
      )}
    </div>
  );
}
