import { ClipboardCheck, Map } from "lucide-react";
import Link from "next/link";
import { InstrumentPanel } from "@/components/layout/instrument-panel";
import { PageHeading } from "@/components/layout/page-heading";
import { Button } from "@/components/ui/button";
import { getLatestCompletedAssessment } from "@/lib/data-access/assessments";
import { getCompany } from "@/lib/data-access/companies";
import { orNotFound, requireOrgPageContext } from "@/lib/data-access/page-context";
import { listRoadmapItemsFor } from "@/lib/data-access/roadmap";
import { GenerateRoadmapButton, RoadmapItemCard } from "./roadmap-view";

export const metadata = { title: "Roadmap" };

export default async function RoadmapPage({
  params,
}: {
  params: Promise<{ companyId: string }>;
}) {
  const { companyId } = await params;
  const ctx = await requireOrgPageContext();

  const [company, assessment] = await orNotFound(() =>
    Promise.all([
      getCompany(ctx, companyId),
      getLatestCompletedAssessment(ctx, companyId),
    ]),
  );
  const items = assessment ? await listRoadmapItemsFor(ctx, assessment) : [];
  const doneCount = items.filter((i) => i.status === "done").length;

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <PageHeading
        eyebrow="IPO preparation roadmap"
        title={company.name}
        description={
          items.length > 0
            ? `${doneCount} of ${items.length} steps done — generated by rules from your readiness assessment.`
            : "A prioritised action plan generated from your readiness assessment."
        }
        actions={
          assessment ? (
            <GenerateRoadmapButton
              assessmentId={assessment.id}
              companyId={company.id}
              hasItems={items.length > 0}
            />
          ) : undefined
        }
      />

      {!assessment ? (
        <InstrumentPanel className="border-dashed">
          <div className="flex flex-col items-center gap-4 py-12 text-center">
            <div className="flex size-14 items-center justify-center rounded-full bg-muted">
              <ClipboardCheck className="size-6 text-primary" />
            </div>
            <div className="space-y-1">
              <p className="font-semibold text-primary">No completed assessment yet</p>
              <p className="max-w-sm text-sm text-muted-foreground">
                The roadmap is derived from your readiness answers — complete the
                assessment first.
              </p>
            </div>
            <Button asChild>
              <Link href={`/companies/${company.id}/assessment`}>
                Start the assessment
              </Link>
            </Button>
          </div>
        </InstrumentPanel>
      ) : items.length === 0 ? (
        <InstrumentPanel className="border-dashed">
          <div className="flex flex-col items-center gap-4 py-12 text-center">
            <div className="flex size-14 items-center justify-center rounded-full bg-muted">
              <Map className="size-6 text-primary" />
            </div>
            <p className="max-w-sm text-sm text-muted-foreground">
              Generate the roadmap to turn the weaknesses detected in the assessment
              into an ordered action plan.
            </p>
          </div>
        </InstrumentPanel>
      ) : (
        <div>
          <ol aria-label="IPO preparation roadmap" className="space-y-3">
            {items.map((item, index) => (
              <RoadmapItemCard
                key={item.id}
                item={item}
                index={index}
                companyId={company.id}
              />
            ))}
          </ol>
          <p className="pt-4 font-utility text-[0.6875rem] text-muted-foreground">
            Rules {items[0].rulesVersion} · assessment of{" "}
            {assessment.completedAt!.toLocaleDateString("en-GB", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
            . Durations are indicative planning estimates.
          </p>
        </div>
      )}
    </div>
  );
}
